# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  friends-of-frieda-garcia-park.com:
    site_hosts:
      - canonical: friends-of-frieda-garcia-park.test
        redirects:
          - www.friends-of-frieda-garcia-park.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@friends-of-frieda-garcia-park.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
